# =========================================================
# Create Signal Linelists - non-NYC version wired to real incident dataset
# archive_deduped comes from unrestricted ESSENCE data
# v2 comes from study_data_long generated by the incident script
# =========================================================

library(dplyr)
library(stringi)
library(stringr)
library(ggplot2)
library(scales)
library(MMWRweek)
library(openxlsx)

# -----------------------------
# User settings
# -----------------------------
project_dir <- "C:/Users/nj7786/Documents/treescan_project"
results_file <- file.path(project_dir, "Results_20250629.csv")
common_cause_file <- file.path(project_dir, "data", "common cause file final.csv")
tree_file <- "C:/Users/nj7786/Documents/treescan_project/data/Tree_File_2025_wide_format.txt"
output_dir <- file.path(project_dir, "output")

dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
setwd(project_dir)

# Pull years for unrestricted ESSENCE archive
pull_years <- 2021:2026

# -----------------------------
# Helpers
# -----------------------------
clean_zip5 <- function(x) {
  x <- as.character(x)
  x <- gsub("[^0-9]", "", x)
  x <- substr(x, 1, 5)
  x[x == ""] <- NA_character_
  x
}

clean_dx <- function(x) {
  x <- as.character(x)
  x <- trimws(x)
  x <- gsub("\\.", "", x)
  x <- toupper(x)
  x[x %in% c("", "NA", "N/A", "<NA>")] <- NA_character_
  x
}

make_age_group <- function(age) {
  age <- suppressWarnings(as.numeric(age))
  case_when(
    is.na(age) ~ NA_character_,
    age < 1 ~ "<1",
    age >= 1 & age <= 4 ~ "1-4",
    age >= 5 & age <= 12 ~ "5-12",
    age >= 13 & age <= 17 ~ "13-17",
    age >= 18 & age <= 49 ~ "18-49",
    age >= 50 & age <= 64 ~ "50-64",
    age >= 65 & age <= 79 ~ "65-79",
    age >= 80 ~ "80+",
    TRUE ~ NA_character_
  )
}

make_dispo <- function(x) {
  x <- as.character(x)
  ifelse(
    x %in% c("09","9","09A","Adm","ADM","20","_Expired","Expired",
             "22","23","24","25","26","27","28","29","40","41","42"),
    "A", "V"
  )
}

get_signal_codes <- function(node_id) {
  x <- gsub("0\\-|1\\-|2\\-", "", as.character(node_id))
  x <- gsub("\\.", "", x)
  x <- trimws(x)
  parts <- unlist(strsplit(x, "\\|"))
  parts <- trimws(parts)
  parts <- parts[parts != ""]
  unique(parts)
}

safe_word_freq <- function(x) {
  stop_words <- c(
    "", "I10", "THE", "A", "AN", "OF", "AND", "TO", "IN", "FOR", "WITH",
    "ON", "IS", "WAS", "ARE", "BY", "AT", "FROM", "MY", "HIS", "HER",
    "HE", "SHE", "AS", "PER", "I", "HAS", "HAVE", "PT", "PATIENT", "STATES"
  )
  
  x <- x[!is.na(x)]
  if (length(x) == 0) return(data.frame(CC_word = character(), Freq = integer()))
  
  words <- toupper(unlist(lapply(
    strsplit(gsub("[[:punct:]]", " ", x), " "),
    unique
  )))
  
  out <- as.data.frame(table(words), stringsAsFactors = FALSE)
  names(out) <- c("CC_word", "Freq")
  out <- out[!out$CC_word %in% stop_words, , drop = FALSE]
  out <- out[nchar(out$CC_word) >= 2, , drop = FALSE]
  out <- out[order(-out$Freq, out$CC_word), , drop = FALSE]
  rownames(out) <- NULL
  out
}

process_dx_groups <- function(x) {
  x <- x[!is.na(x)]
  if (length(x) == 0) return(data.frame(dx = character(), Freq = integer()))
  
  process_one <- function(one) {
    tokens <- unlist(strsplit(one, " "))
    tokens <- tokens[tokens != ""]
    unique(substr(tokens, 1, 3))
  }
  
  out <- unlist(lapply(x, process_one))
  out <- trimws(out)
  out <- out[out != ""]
  if (length(out) == 0) return(data.frame(dx = character(), Freq = integer()))
  
  data.frame(table(dx = out), stringsAsFactors = FALSE)
}

safe_test_p <- function(tbl) {
  result <- tryCatch({
    res <- suppressWarnings(chisq.test(tbl))
    if (any(is.na(res$expected)) || any(res$expected < 5)) stop("Invalid expected values")
    list(p.value = res$p.value, method = res$method)
  }, warning = function(w) {
    if (all(dim(tbl) == c(2, 2))) {
      res <- fisher.test(tbl)
      list(p.value = res$p.value, method = res$method)
    } else {
      res <- chisq.test(tbl, simulate.p.value = TRUE, B = 10000)
      list(p.value = res$p.value, method = "Simulated Chi-squared Test")
    }
  }, error = function(e) {
    if (all(dim(tbl) == c(2, 2))) {
      res <- fisher.test(tbl)
      list(p.value = res$p.value, method = res$method)
    } else {
      res <- chisq.test(tbl, simulate.p.value = TRUE, B = 10000)
      list(p.value = res$p.value, method = "Simulated Chi-squared Test")
    }
  })
  result
}

save_plot_png <- function(plot_expr, file, width = 1000, height = 600, res = 150) {
  png(file, width = width, height = height, res = res)
  plot_expr()
  dev.off()
}

# -----------------------------
# 1. TreeScan results
# -----------------------------
TS_Results_today <- read.csv(results_file, stringsAsFactors = FALSE)

TS_Results_today <- TS_Results_today[!is.na(TS_Results_today$Recurrence.Interval), ]
TS_Results_today <- TS_Results_today[TS_Results_today$Relative.Risk >= 1.3, ]
TS_Results_today <- TS_Results_today[
  (TS_Results_today$Recurrence.Interval >= 365) |
    (grepl("1\\-", TS_Results_today$Node.Identifier) &
       TS_Results_today$Recurrence.Interval >= 100),
]

library(stringi)

TS_Results_today$Node.Identifier <- stri_replace_all_fixed(
  TS_Results_today$Node.Identifier, "\xa0", ""
)

# -----------------------------
# 2. Common cause expansion
# -----------------------------
common_cause <- read.csv(common_cause_file, stringsAsFactors = FALSE)
common_cause <- common_cause[!is.na(common_cause$X4), ]

common_cause_codes <- TS_Results_today$Node.Identifier[
  grepl(
    paste(common_cause$X2, collapse = "|"),
    gsub("2\\-|1\\-|0\\-", "", TS_Results_today$Node.Identifier)
  )
]

if (length(common_cause_codes) > 0) {
  for (i in seq_along(common_cause_codes)) {
    idx <- grepl(
      paste(gsub("2\\-", "2\\\\-", gsub("1\\-", "1\\\\-", common_cause_codes[i]))),
      TS_Results_today$Node.Identifier
    )
    
    TS_Results_today$Node.Name[idx] <- TS_Results_today$Node.Identifier[idx]
    
    list_codes <- common_cause$X1[
      grepl(
        paste(gsub("1\\-|2\\-", "", common_cause_codes[i])),
        common_cause$X2
      )
    ]
    
    TS_Results_today$Node.Identifier[
      grepl(paste(common_cause_codes[i]), TS_Results_today$Node.Identifier)
    ] <- paste0(
      c(
        TS_Results_today$Node.Name[
          grepl(paste(common_cause_codes[i]), TS_Results_today$Node.Identifier)
        ],
        list_codes
      ),
      collapse = "|"
    )
  }
}

# -----------------------------
# 3. Pull unrestricted ESSENCE data and build archive_deduped
# Assumes download_nssp_chunked_year() already exists
# -----------------------------
message("Downloading unrestricted ESSENCE yearly data...")
yearly_list <- lapply(pull_years, download_nssp_chunked_year)
names(yearly_list) <- pull_years
raw_ed <- bind_rows(yearly_list)

archive_deduped <- raw_ed %>%
  mutate(
    date = as.Date(C_Visit_Date_Time),
    time = format(as.POSIXct(C_Visit_Date_Time), "%H:%M"),
    key = as.character(C_Unique_Patient_ID),
    hospital = as.character(Hospital),
    zipcode = clean_zip5(Patient_Zip),
    patientid = as.character(C_Unique_Patient_ID),
    sex = NA_character_,
    age = suppressWarnings(as.numeric(Age)),
    age_group = make_age_group(age),
    race = NA_character_,
    ethnicity = NA_character_,
    chiefcomplaint = as.character(ChiefComplaintParsed),
    admitreason = NA_character_,
    diagnosiscode = as.character(DischargeDiagnosis),
    diagnosistext = as.character(DischargeDiagnosis),
    diagnosiscode1 = clean_dx(DischargeDiagnosis),
    modeofarrival = NA_character_,
    travelhistory = NA_character_,
    dischargedisposition = as.character(DischargeDisposition),
    dispo = make_dispo(DischargeDisposition),
    dischargedate = as.Date(NA),
    triagenote = NA_character_,
    region = as.character(Region),
    region_group = ifelse(is.na(Region) | trimws(Region) == "", "Unknown", as.character(Region))
  ) %>%
  filter(!is.na(diagnosiscode1)) %>%
  select(
    date, time, key, hospital, zipcode, patientid, sex, age, age_group,
    race, ethnicity, chiefcomplaint, admitreason, diagnosiscode, diagnosistext,
    diagnosiscode1, modeofarrival, travelhistory, dischargedisposition, dispo,
    dischargedate, triagenote, region, region_group
  )

# -----------------------------
# 4. Build v2 from study_data_long
# IMPORTANT: this must already exist in memory from your incident script
# -----------------------------
v2 <- study_data_long %>%
  transmute(
    date = as.Date(date),
    key = as.character(key),
    dispo = as.character(severity),
    code = clean_dx(code)
  ) %>%
  filter(!is.na(code))

# -----------------------------
# 5. Build ed for trends
# -----------------------------
ed <- archive_deduped %>%
  transmute(
    date = as.Date(date),
    hospital = hospital,
    diagnosiscode = diagnosiscode,
    dischargedisposition = dischargedisposition,
    dispo = dispo,
    diagnosiscode1 = diagnosiscode1
  )

ed <- cbind(MMWRweek(ed$date), ed)
mmwrwks <- unique(MMWRweek(unique(ed$date))[ , -3])

yr_list <- (as.numeric(format(max(archive_deduped$date, na.rm = TRUE), "%Y")) - 3):
  as.numeric(format(max(archive_deduped$date, na.rm = TRUE), "%Y"))

end <- max(archive_deduped$date, na.rm = TRUE)

# -----------------------------
# 6. Load tree file
# -----------------------------
icd10.2026_treefilew_FINAL <- icd10_treefilew_f

# -----------------------------
# 7. Main loop
# -----------------------------
sigs_maxout <- character()

for (i in seq_len(nrow(TS_Results_today))) {
  
  signal_id_raw <- TS_Results_today$Node.Identifier[i]
  signal_codes <- get_signal_codes(signal_id_raw)
  signal_start <- as.Date(TS_Results_today$Time.Window.Start[i])
  
  message(sprintf("Processing signal %d of %d: %s", i, nrow(TS_Results_today), signal_id_raw))
  
  temp <- archive_deduped[
    archive_deduped$diagnosiscode1 %in% signal_codes &
      archive_deduped$date >= signal_start,
    c("date","time","key","hospital","zipcode","patientid","sex","age","age_group",
      "race","ethnicity","chiefcomplaint","admitreason","diagnosiscode","diagnosistext",
      "diagnosiscode1","modeofarrival","travelhistory","dischargedisposition","dispo",
      "dischargedate","triagenote","region","region_group")
  ]
  
  temp1 <- archive_deduped[
    archive_deduped$diagnosiscode1 %in% signal_codes &
      archive_deduped$date < signal_start,
    c("date","time","key","hospital","zipcode","patientid","sex","age","age_group",
      "race","ethnicity","chiefcomplaint","admitreason","diagnosiscode","diagnosistext",
      "diagnosiscode1","modeofarrival","travelhistory","dischargedisposition","dispo",
      "dischargedate","triagenote","region","region_group")
  ]
  
  temp2 <- v2[
    v2$code %in% signal_codes &
      as.Date(v2$date) >= signal_start,
    1:3
  ]
  
  temp21 <- v2[
    v2$code %in% signal_codes &
      as.Date(v2$date) < signal_start,
    1:3
  ]
  
  ed_keep <- ed[ed$diagnosiscode1 %in% signal_codes, , drop = FALSE]
  if (nrow(ed_keep) > 0) {
    ed_keep$n <- 1
  } else {
    ed_keep$n <- integer(0)
  }
  
  if (nrow(temp) == 0) {
    message(sprintf("Skipping %s: no cluster records found.", signal_id_raw))
    next
  }
  
  # merge incident dataset into cluster
  if (nrow(temp2) > 0) {
    temp2$dxtype <- ifelse(temp2$dispo == "A", 1, 0)
    temp2 <- temp2[, -3, drop = FALSE]
    temp$date <- as.Date(temp$date)
    temp2$date <- as.Date(temp2$date)
    temp <- merge(temp, temp2, by = c("date", "key"), all.x = TRUE)
    temp <- temp[, c(ncol(temp), 1:(ncol(temp) - 1))]
    temp$dxtype[is.na(temp$dxtype)] <- -1
  } else {
    temp$dxtype <- -1
  }
  
  # merge incident dataset into baseline
  if (nrow(temp21) > 0 && nrow(temp1) > 0) {
    temp21$dxtype <- ifelse(temp21$dispo == "A", 1, 0)
    temp21 <- temp21[, -3, drop = FALSE]
    temp1$date <- as.Date(temp1$date)
    temp21$date <- as.Date(temp21$date)
    temp1 <- merge(temp1, temp21, by = c("date", "key"), all.x = TRUE)
    temp1 <- temp1[, c(ncol(temp1), 1:(ncol(temp1) - 1))]
    temp1$dxtype[is.na(temp1$dxtype)] <- -1
  } else if (nrow(temp1) > 0) {
    temp1$dxtype <- -1
  }
  
  # if 1- node, keep only adverse
  if (grepl("1\\-", signal_id_raw)) {
    temp <- temp[temp$dispo == "A", , drop = FALSE]
    if (nrow(temp1) > 0) temp1 <- temp1[temp1$dispo == "A", , drop = FALSE]
    ed_keep <- ed_keep[ed_keep$dispo == "A", , drop = FALSE]
  }
  
  if (nrow(temp) > 0) {
    temp$time <- format(strptime(temp$time, "%H:%M"), "%H:%M")
    temp <- temp[order(temp$date, temp$time), ]
  }
  
  if (nrow(temp1) > 0) {
    temp1$time <- format(strptime(temp1$time, "%H:%M"), "%H:%M")
    temp1 <- temp1[order(temp1$date, temp1$time), ]
  }
  
  # -----------------------------
  # Trends
  # -----------------------------
  if (nrow(ed_keep) > 0) {
    ed_keep <- cbind(MMWRweek(ed_keep$date)[, -3], ed_keep)
    ed_keep <- aggregate(n ~ MMWRyear + MMWRweek, data = ed_keep, sum)
    ed_keep <- merge(mmwrwks, ed_keep, all.x = TRUE)
    ed_keep$n[is.na(ed_keep$n)] <- 0
    ed_keep <- ed_keep[ed_keep$MMWRyear %in% yr_list, ]
    ed_keep <- ed_keep[order(ed_keep$MMWRyear, ed_keep$MMWRweek), ]
    rownames(ed_keep) <- seq_len(nrow(ed_keep))
  } else {
    ed_keep <- data.frame(MMWRyear = integer(), MMWRweek = integer(), n = integer())
  }
  
  code_trend <- tempfile(fileext = ".png")
  
  if (nrow(ed_keep) > 0) {
    complete_week <- ifelse(
      weekdays(end) == "Saturday",
      ed_keep$MMWRweek[nrow(ed_keep)],
      ed_keep$MMWRweek[max(1, nrow(ed_keep) - 1)]
    )
    
    idx_exclude <- seq(max(1, nrow(ed_keep) - 1), nrow(ed_keep))
    idx_pool <- setdiff(seq_len(nrow(ed_keep)), idx_exclude)
    
    hlm_weeks <- which(ed_keep$MMWRweek[idx_pool] == complete_week)
    hlm_weeks <- c(hlm_weeks - 1, hlm_weeks, hlm_weeks + 1)
    hlm_weeks <- hlm_weeks[hlm_weeks >= 1 & hlm_weeks <= nrow(ed_keep)]
    
    hlm_data <- ed_keep[hlm_weeks, , drop = FALSE]
    hlm_data <- hlm_data[order(hlm_data$MMWRyear, hlm_data$MMWRweek), , drop = FALSE]
    
    current_year <- max(ed_keep$MMWRyear, na.rm = TRUE)
    current_count <- ed_keep$n[ed_keep$MMWRyear == current_year & ed_keep$MMWRweek == complete_week]
    
    if (length(current_count) > 0 && nrow(hlm_data) > 1) {
      if (current_count > mean(hlm_data$n) + 2 * sd(hlm_data$n)) {
        sigs_maxout <- c(sigs_maxout, as.character(signal_id_raw))
      }
    }
    
    save_plot_png(function() {
      par(mar = c(6, 4, 1, 2))
      plot(
        1:52, rep(0, 52),
        type = "n",
        xlim = c(1, 52),
        ylim = c(0, ceiling(max(ed_keep$n, na.rm = TRUE) * 1.1 + 1)),
        xlab = "CDC_Week",
        ylab = gsub("2\\-", "", paste(signal_id_raw)),
        xaxt = "n"
      )
      axis(1, at = seq(1, 52, 2), labels = seq(1, 52, 2), cex.axis = 0.6, las = 2)
      
      years_here <- sort(unique(ed_keep$MMWRyear))
      cols <- c("blue", "green4", "purple", "red", "orange", "black")
      lwds <- c(rep(1, max(1, length(years_here) - 1)), 3)
      
      for (k in seq_along(years_here)) {
        yy <- years_here[k]
        lines(
          ed_keep$MMWRweek[ed_keep$MMWRyear == yy],
          ed_keep$n[ed_keep$MMWRyear == yy],
          col = cols[min(k, length(cols))],
          lwd = lwds[min(k, length(lwds))]
        )
      }
      
      legend("topleft", lty = 1, col = cols[seq_along(years_here)],
             legend = years_here, bty = "n", ncol = min(4, length(years_here)))
    }, code_trend)
  } else {
    save_plot_png(function() {
      plot.new()
      text(0.5, 0.5, "No trend data available")
    }, code_trend)
  }
  
  # -----------------------------
  # Geography substitute
  # -----------------------------
  temp$zipcode <- clean_zip5(temp$zipcode)
  if (nrow(temp1) > 0) temp1$zipcode <- clean_zip5(temp1$zipcode)
  
  zip_chart <- tempfile(fileext = ".png")
  region_chart <- tempfile(fileext = ".png")
  
  save_plot_png(function() {
    if (nrow(temp) == 0 || all(is.na(temp$zipcode))) {
      plot.new()
      text(0.5, 0.5, "No cluster ZIP data available")
    } else {
      zip_df <- as.data.frame(table(temp$zipcode), stringsAsFactors = FALSE)
      names(zip_df) <- c("zipcode", "Freq")
      zip_df <- zip_df[!is.na(zip_df$zipcode) & zip_df$zipcode != "", , drop = FALSE]
      zip_df <- zip_df[order(-zip_df$Freq, zip_df$zipcode), , drop = FALSE]
      zip_df <- head(zip_df, 15)
      
      par(mar = c(10, 4, 4, 2))
      barplot(
        zip_df$Freq,
        names.arg = zip_df$zipcode,
        las = 2,
        cex.names = 0.7,
        ylab = "Count",
        main = "Top patient ZIP codes in cluster"
      )
    }
  }, zip_chart)
  
  save_plot_png(function() {
    reg_cluster <- as.data.frame(table(temp$region_group), stringsAsFactors = FALSE)
    names(reg_cluster) <- c("region_group", "ClusterFreq")
    
    if (nrow(temp1) > 0) {
      reg_base <- as.data.frame(table(temp1$region_group), stringsAsFactors = FALSE)
      names(reg_base) <- c("region_group", "BaselineFreq")
      reg_df <- merge(reg_cluster, reg_base, by = "region_group", all = TRUE)
      reg_df$ClusterFreq[is.na(reg_df$ClusterFreq)] <- 0
      reg_df$BaselineFreq[is.na(reg_df$BaselineFreq)] <- 0
      reg_df$Diff <- reg_df$ClusterFreq - reg_df$BaselineFreq
      reg_df <- reg_df[order(-reg_df$Diff, reg_df$region_group), , drop = FALSE]
      
      par(mar = c(10, 4, 4, 2))
      barplot(
        reg_df$Diff,
        names.arg = reg_df$region_group,
        las = 2,
        cex.names = 0.7,
        ylab = "Count difference",
        main = "Region difference: cluster minus baseline"
      )
    } else {
      reg_df <- reg_cluster[order(-reg_cluster$ClusterFreq, reg_cluster$region_group), , drop = FALSE]
      par(mar = c(10, 4, 4, 2))
      barplot(
        reg_df$ClusterFreq,
        names.arg = reg_df$region_group,
        las = 2,
        cex.names = 0.7,
        ylab = "Count",
        main = "Cluster counts by region"
      )
    }
  }, region_chart)
  
  # -----------------------------
  # Other codes
  # -----------------------------
  temp3c <- data.frame(Level4 = character(), ClusterFreq = integer(), Desc = character(), ClusterPct = numeric())
  temp3b <- data.frame(Level4 = character(), BaselineFreq = integer(), Desc = character(), BaselinePct = numeric())
  
  cluster_dx_source <- temp[which(temp$dxtype != -1), "diagnosiscode1"]
  cluster_dx_source <- gsub("\\|", "", cluster_dx_source)
  cluster_freq <- process_dx_groups(cluster_dx_source)
  
  if (nrow(cluster_freq) > 0) {
    cluster_freq$dx <- gsub("\\s+", "", cluster_freq$dx)
    temp3c <- merge(
      cluster_freq,
      icd10.2026_treefilew_FINAL[, c("Name1", "Desc")],
      by.x = "dx", by.y = "Name1", all.x = TRUE
    )
    temp3c <- temp3c[order(-temp3c$Freq, temp3c$dx), , drop = FALSE]
    names(temp3c)[1:2] <- c("Level4", "ClusterFreq")
    temp3c$ClusterPct <- round((temp3c$ClusterFreq * 100) / max(1, length(cluster_dx_source)), 1)
  }
  
  if (nrow(temp1) > 0) {
    baseline_dx_source <- temp1[which(temp1$dxtype != -1), "diagnosiscode1"]
    baseline_dx_source <- gsub("\\|", "", baseline_dx_source)
    baseline_freq <- process_dx_groups(baseline_dx_source)
    
    if (nrow(baseline_freq) > 0) {
      baseline_freq$dx <- gsub("\\s+", "", baseline_freq$dx)
      temp3b <- merge(
        baseline_freq,
        icd10.2026_treefilew_FINAL[, c("Name1", "Desc")],
        by.x = "dx", by.y = "Name1", all.x = TRUE
      )
      temp3b <- temp3b[order(-temp3b$Freq, temp3b$dx), , drop = FALSE]
      names(temp3b)[1:2] <- c("Level4", "BaselineFreq")
      temp3b$BaselinePct <- round((temp3b$BaselineFreq * 100) / max(1, length(baseline_dx_source)), 1)
    }
  }
  
  # -----------------------------
  # Chief complaint words
  # -----------------------------
  cluster_words <- safe_word_freq(temp$chiefcomplaint[which(temp$dxtype != -1)])
  if (nrow(cluster_words) > 0) {
    names(cluster_words) <- c("CC_word", "ClusterFreq")
    cluster_words$ClusterPct <- round(
      (cluster_words$ClusterFreq * 100) /
        max(1, length(temp$chiefcomplaint[which(temp$dxtype != -1)])),
      1
    )
  }
  
  if (nrow(temp1) > 0) {
    baseline_words <- safe_word_freq(temp1$chiefcomplaint[which(temp1$dxtype != -1)])
    if (nrow(baseline_words) > 0) {
      names(baseline_words) <- c("CC_word", "BaselineFreq")
      baseline_words$BaselinePct <- round(
        (baseline_words$BaselineFreq * 100) /
          max(1, length(temp1$chiefcomplaint[which(temp1$dxtype != -1)])),
        1
      )
      temp_words <- merge(cluster_words, baseline_words, by = "CC_word", all = TRUE)
      temp_words <- temp_words[order(-temp_words$ClusterFreq, temp_words$CC_word), , drop = FALSE]
    } else {
      temp_words <- cluster_words
    }
  } else {
    temp_words <- cluster_words
  }
  
  # -----------------------------
  # Demographics
  # Since sex/race/ethnicity missing, use age_group + region_group only
  # -----------------------------
  demog_table <- data.frame()
  
  temp_d <- temp[which(temp$dxtype != -1), c("age_group", "region_group")]
  temp_d$group <- "Cluster"
  
  if (nrow(temp1) > 0) {
    temp1_d <- temp1[which(temp1$dxtype != -1), c("age_group", "region_group")]
    temp1_d$group <- "Baseline"
    combined <- rbind(temp_d, temp1_d)
    
    demographics <- c("age_group", "region_group")
    results <- list()
    
    for (var in demographics) {
      tab <- table(combined[[var]], combined$group)
      prop <- round(prop.table(table(combined[[var]], combined$group), margin = 2) * 100, 2)
      combined_prop <- as.data.frame.matrix(prop)
      combined_prop$Variable <- rownames(combined_prop)
      rownames(combined_prop) <- NULL
      
      test_res <- safe_test_p(tab)
      
      combined_prop$p_value <- ""
      combined_prop$p_value[1] <- round(test_res$p.value, 3)
      combined_prop$method <- ""
      combined_prop$method[1] <- test_res$method
      combined_prop$Demographic <- var
      
      combined_prop <- combined_prop[, c("Demographic", "Variable", "Baseline", "Cluster", "p_value", "method")]
      results[[var]] <- combined_prop
    }
    
    demog_table <- do.call(rbind, results)
    rownames(demog_table) <- NULL
    demog_table$Diff <- round(demog_table$Cluster - demog_table$Baseline, 2)
    demog_table <- demog_table[, c("Demographic","Variable","Cluster","Baseline","Diff","p_value","method")]
    names(demog_table) <- c(
      "Demographic","Variable","ClusterPercent","BaselinePercent",
      "ClusterMinusBaselinePercent","ChiSq_Fis_Pval","Method"
    )
    
  } else {
    combined <- temp_d
    demographics <- c("age_group", "region_group")
    results <- list()
    
    for (var in demographics) {
      prop <- round(prop.table(table(combined[[var]])) * 100, 2)
      combined_prop <- as.data.frame(prop, stringsAsFactors = FALSE)
      combined_prop$Variable <- combined_prop$Var1
      rownames(combined_prop) <- NULL
      combined_prop$Demographic <- var
      combined_prop$Cluster <- combined_prop$Freq
      combined_prop <- combined_prop[, c("Demographic", "Variable", "Cluster")]
      results[[var]] <- combined_prop
    }
    
    demog_table <- do.call(rbind, results)
    rownames(demog_table) <- NULL
    demog_table <- demog_table[, c("Demographic","Variable","Cluster")]
    names(demog_table) <- c("Demographic","Variable","ClusterPercent")
  }
  
  # -----------------------------
  # Hospital graph
  # -----------------------------
  hospital_barplot <- tempfile(fileext = ".png")
  
  save_plot_png(function() {
    if (nrow(temp1) > 0) {
      hosp_c <- data.frame(table(temp$hospital[which(temp$dxtype != -1)]) / max(1, nrow(temp[which(temp$dxtype != -1), ])))
      hosp_b <- data.frame(table(temp1$hospital[which(temp1$dxtype != -1)]) / max(1, nrow(temp1[which(temp1$dxtype != -1), ])))
      names(hosp_c) <- c("hospital","ClusterPct")
      names(hosp_b) <- c("hospital","BaselinePct")
      hosp_cb <- merge(hosp_c, hosp_b, by = "hospital", all = TRUE)
      hosp_cb$ClusterPct[is.na(hosp_cb$ClusterPct)] <- 0
      hosp_cb$BaselinePct[is.na(hosp_cb$BaselinePct)] <- 0
      hosp_cb$diff <- hosp_cb$ClusterPct - hosp_cb$BaselinePct
      hosp_cb <- hosp_cb[order(-hosp_cb$diff, hosp_cb$hospital), , drop = FALSE]
      hosp_cb$hospital <- gsub("HOSPITAL","HOSP", hosp_cb$hospital)
      hosp_cb$hospital <- gsub("MEDICAL","MED", hosp_cb$hospital)
      hosp_cb$hospital <- gsub("CENTER","CTR", hosp_cb$hospital)
      
      par(mar = c(10, 4, 4, 2))
      barplot(
        hosp_cb$diff * 100,
        ylab = "%",
        names.arg = hosp_cb$hospital,
        las = 2,
        cex.names = 0.35,
        main = "Difference in percent of ED visits by hospital\nbetween cluster and baseline periods",
        cex.main = 0.8
      )
    } else {
      hosp_c <- data.frame(table(temp$hospital[which(temp$dxtype != -1)]) / max(1, nrow(temp[which(temp$dxtype != -1), ])))
      names(hosp_c) <- c("hospital","ClusterPct")
      hosp_c$hospital <- gsub("HOSPITAL","HOSP", hosp_c$hospital)
      hosp_c$hospital <- gsub("MEDICAL","MED", hosp_c$hospital)
      hosp_c$hospital <- gsub("CENTER","CTR", hosp_c$hospital)
      hosp_c <- hosp_c[order(-hosp_c$ClusterPct, hosp_c$hospital), , drop = FALSE]
      
      par(mar = c(10, 4, 4, 2))
      barplot(
        hosp_c$ClusterPct * 100,
        ylab = "%",
        names.arg = hosp_c$hospital,
        las = 2,
        cex.names = 0.35,
        main = "Percent of ED visits by hospital for cluster",
        cex.main = 0.8
      )
    }
  }, hospital_barplot)
  
  # -----------------------------
  # Geography tables
  # -----------------------------
  cluster_region_table <- as.data.frame(table(temp$region_group), stringsAsFactors = FALSE)
  names(cluster_region_table) <- c("region_group", "ClusterCount")
  cluster_region_table$ClusterPct <- round(cluster_region_table$ClusterCount * 100 / max(1, sum(cluster_region_table$ClusterCount)), 1)
  cluster_region_table <- cluster_region_table[order(-cluster_region_table$ClusterCount, cluster_region_table$region_group), , drop = FALSE]
  
  baseline_region_table <- data.frame()
  if (nrow(temp1) > 0) {
    baseline_region_table <- as.data.frame(table(temp1$region_group), stringsAsFactors = FALSE)
    names(baseline_region_table) <- c("region_group", "BaselineCount")
    baseline_region_table$BaselinePct <- round(baseline_region_table$BaselineCount * 100 / max(1, sum(baseline_region_table$BaselineCount)), 1)
    baseline_region_table <- baseline_region_table[order(-baseline_region_table$BaselineCount, baseline_region_table$region_group), , drop = FALSE]
  }
  
  cluster_zip_table <- as.data.frame(table(temp$zipcode), stringsAsFactors = FALSE)
  names(cluster_zip_table) <- c("zipcode", "ClusterCount")
  cluster_zip_table <- cluster_zip_table[!is.na(cluster_zip_table$zipcode) & cluster_zip_table$zipcode != "", , drop = FALSE]
  cluster_zip_table$ClusterPct <- round(cluster_zip_table$ClusterCount * 100 / max(1, sum(cluster_zip_table$ClusterCount)), 1)
  cluster_zip_table <- cluster_zip_table[order(-cluster_zip_table$ClusterCount, cluster_zip_table$zipcode), , drop = FALSE]
  
  baseline_zip_table <- data.frame()
  if (nrow(temp1) > 0) {
    baseline_zip_table <- as.data.frame(table(temp1$zipcode), stringsAsFactors = FALSE)
    names(baseline_zip_table) <- c("zipcode", "BaselineCount")
    baseline_zip_table <- baseline_zip_table[!is.na(baseline_zip_table$zipcode) & baseline_zip_table$zipcode != "", , drop = FALSE]
    baseline_zip_table$BaselinePct <- round(baseline_zip_table$BaselineCount * 100 / max(1, sum(baseline_zip_table$BaselineCount)), 1)
    baseline_zip_table <- baseline_zip_table[order(-baseline_zip_table$BaselineCount, baseline_zip_table$zipcode), , drop = FALSE]
  }
  
  # -----------------------------
  # Workbook
  # -----------------------------
  wb <- createWorkbook()
  
  addWorksheet(wb, "ClusterLinelist")
  writeData(wb, "ClusterLinelist", temp, withFilter = TRUE)
  
  addWorksheet(wb, "BaselineLinelist")
  if (nrow(temp1) > 0) {
    writeData(wb, "BaselineLinelist", temp1, withFilter = TRUE)
  } else {
    writeData(wb, "BaselineLinelist", data.frame(Note = "No baseline records for this signal"))
  }
  
  addWorksheet(wb, "Other_Codes")
  if (nrow(temp3c) > 0) {
    writeData(wb, "Other_Codes", temp3c[, c("Level4","Desc","ClusterFreq","ClusterPct")], startRow = 1, startCol = 1)
  }
  if (nrow(temp3b) > 0) {
    writeData(wb, "Other_Codes", temp3b[, c("Level4","Desc","BaselineFreq","BaselinePct")], startRow = 1, startCol = 6)
  }
  
  addWorksheet(wb, "TopCC_words")
  if (exists("temp_words") && nrow(temp_words) > 0) {
    writeData(wb, "TopCC_words", temp_words)
  } else {
    writeData(wb, "TopCC_words", data.frame(Note = "No chief complaint word data available"))
  }
  
  addWorksheet(wb, "Trends")
  insertImage(wb, sheet = "Trends", file = code_trend, startRow = 1, startCol = 1, width = 10, height = 6)
  
  addWorksheet(wb, "Geography")
  insertImage(wb, sheet = "Geography", file = zip_chart, startRow = 1, startCol = 1, width = 10, height = 6)
  insertImage(wb, sheet = "Geography", file = region_chart, startRow = 25, startCol = 1, width = 10, height = 6)
  
  writeData(wb, "Geography", "Cluster ZIP distribution", startRow = 1, startCol = 12)
  if (nrow(cluster_zip_table) > 0) {
    writeData(wb, "Geography", cluster_zip_table, startRow = 2, startCol = 12)
  }
  
  if (nrow(baseline_zip_table) > 0) {
    writeData(wb, "Geography", "Baseline ZIP distribution", startRow = 1, startCol = 17)
    writeData(wb, "Geography", baseline_zip_table, startRow = 2, startCol = 17)
  }
  
  writeData(wb, "Geography", "Cluster region distribution", startRow = 25, startCol = 12)
  if (nrow(cluster_region_table) > 0) {
    writeData(wb, "Geography", cluster_region_table, startRow = 26, startCol = 12)
  }
  
  if (nrow(baseline_region_table) > 0) {
    writeData(wb, "Geography", "Baseline region distribution", startRow = 25, startCol = 17)
    writeData(wb, "Geography", baseline_region_table, startRow = 26, startCol = 17)
  }
  
  addWorksheet(wb, "Hospitals")
  insertImage(wb, sheet = "Hospitals", file = hospital_barplot, startRow = 1, startCol = 1, width = 10, height = 6)
  
  addWorksheet(wb, "Demographics")
  writeData(wb, "Demographics", demog_table)
  
  safe_signal_name <- gsub("[\\|/\\\\:*?\"<>]", "_", gsub("2\\-", "", signal_id_raw))
  out_file <- file.path(output_dir, paste0("Linelist_", safe_signal_name, ".xlsx"))
  saveWorkbook(wb, out_file, overwrite = TRUE)
}

# -----------------------------
# Save max-outlier signals
# -----------------------------
if (length(sigs_maxout) > 0) {
  write.csv(
    data.frame(Node.Identifier = unique(sigs_maxout)),
    file.path(output_dir, "Signals_maxout.csv"),
    row.names = FALSE
  )
}